namespace Warehouse.Core.Infrastructure.Persistence.Migrations

open FluentMigrator

[<Migration(1L, "Initial migration with base tables")>]
type InitialMigration() =
    inherit Migration()

    override this.Up() =
        this.Execute.Sql("CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\";")

        this.Create
            .Table("markets")
            .WithColumn("id")
            .AsInt32()
            .PrimaryKey()
            .Identity()
            .WithColumn("type")
            .AsInt32()
            .NotNullable()
            .WithColumn("created_at")
            .AsDateTime()
            .NotNullable()
            .WithColumn("updated_at")
            .AsDateTime()
            .NotNullable()
        |> ignore

        this.Create.Index().OnTable("markets").OnColumn("type").Ascending().WithOptions().Unique() |> ignore

        this.Create
            .Table("market_credentials")
            .WithColumn("id")
            .AsInt32()
            .PrimaryKey()
            .Identity()
            .WithColumn("market_id")
            .AsInt32()
            .NotNullable()
            .ForeignKey("markets", "id")
            .WithColumn("api_key")
            .AsString(500)
            .NotNullable()
            .WithColumn("secret_key")
            .AsString(500)
            .NotNullable()
            .WithColumn("passphrase")
            .AsString(500)
            .Nullable()
            .WithColumn("is_sandbox")
            .AsBoolean()
            .NotNullable()
            .WithDefaultValue(true)
            .WithColumn("created_at")
            .AsDateTime()
            .NotNullable()
            .WithColumn("updated_at")
            .AsDateTime()
            .NotNullable()
        |> ignore

        this.Create.Index().OnTable("market_credentials").OnColumn("market_id").Ascending().WithOptions().Unique()
        |> ignore

        this.Create
            .Table("pipeline_configurations")
            .WithColumn("id")
            .AsInt32()
            .PrimaryKey()
            .Identity()
            .WithColumn("name")
            .AsString(200)
            .NotNullable()
            .WithColumn("symbol")
            .AsString(20)
            .NotNullable()
            .WithColumn("market_type")
            .AsInt32()
            .NotNullable()
            .WithColumn("enabled")
            .AsBoolean()
            .NotNullable()
            .WithDefaultValue(false)
            .WithColumn("execution_interval")
            .AsInt64()
            .NotNullable()
            .WithColumn("last_executed_at")
            .AsDateTime()
            .Nullable()
            .WithColumn("status")
            .AsInt32()
            .NotNullable()
            .WithColumn("tags")
            .AsCustom("jsonb")
            .WithDefaultValue("[]")
            .WithColumn("created_at")
            .AsDateTime()
            .NotNullable()
            .WithColumn("updated_at")
            .AsDateTime()
            .NotNullable()
        |> ignore

        this.Create
            .Table("positions")
            .WithColumn("id")
            .AsGuid()
            .PrimaryKey()
            .WithDefault(SystemMethods.NewSequentialId)
            .WithColumn("pipeline_id")
            .AsInt32()
            .Nullable()
            .ForeignKey("pipeline_configurations", "id")
            .OnDelete(System.Data.Rule.Cascade)
            .WithColumn("symbol")
            .AsString(20)
            .NotNullable()
            .WithColumn("status")
            .AsInt32()
            .NotNullable()
            .WithColumn("entry_price")
            .AsDecimal(28, 10)
            .Nullable()
            .WithColumn("quantity")
            .AsDecimal(28, 10)
            .Nullable()
            .WithColumn("exit_price")
            .AsDecimal(28, 10)
            .Nullable()
        |> ignore

        this.Create.Index().OnTable("positions").OnColumn("pipeline_id").Ascending().OnColumn("status").Ascending()
        |> ignore

        this.Create
            .Table("candlesticks")
            .WithColumn("id")
            .AsGuid()
            .PrimaryKey()
            .WithDefault(SystemMethods.NewSequentialId)
            .WithColumn("symbol")
            .AsString(20)
            .NotNullable()
            .WithColumn("market_type")
            .AsInt32()
            .NotNullable()
            .WithColumn("timestamp")
            .AsDateTime()
            .NotNullable()
            .WithColumn("timeframe")
            .AsString(10)
            .NotNullable()
            .WithColumn("open")
            .AsDecimal(28, 10)
            .NotNullable()
            .WithColumn("high")
            .AsDecimal(28, 10)
            .NotNullable()
            .WithColumn("low")
            .AsDecimal(28, 10)
            .NotNullable()
            .WithColumn("close")
            .AsDecimal(28, 10)
            .NotNullable()
            .WithColumn("volume")
            .AsDecimal(28, 10)
            .NotNullable()
            .WithColumn("volume_quote")
            .AsDecimal(28, 10)
            .NotNullable()
        |> ignore

        this.Create
            .Index()
            .OnTable("candlesticks")
            .OnColumn("symbol")
            .Ascending()
            .OnColumn("market_type")
            .Ascending()
            .OnColumn("timeframe")
            .Ascending()
            .OnColumn("timestamp")
            .Ascending()
        |> ignore

        this.Create.Index().OnTable("candlesticks").OnColumn("timestamp").Ascending() |> ignore

        this.Create
            .Table("pipeline_steps")
            .WithColumn("id")
            .AsGuid()
            .PrimaryKey()
            .WithDefault(SystemMethods.NewSequentialId)
            .WithColumn("pipeline_details_id")
            .AsInt32()
            .Nullable()
            .ForeignKey("pipeline_configurations", "id")
            .OnDelete(System.Data.Rule.Cascade)
            .WithColumn("name")
            .AsString(200)
            .NotNullable()
            .WithColumn("order")
            .AsInt32()
            .NotNullable()
            .WithColumn("parameters")
            .AsCustom("jsonb")
            .WithDefaultValue("{}")
        |> ignore

        this.Create
            .Index()
            .OnTable("pipeline_steps")
            .OnColumn("pipeline_details_id")
            .Ascending()
            .OnColumn("order")
            .Ascending()
            .WithOptions()
            .Unique()
        |> ignore

        this.Create
            .Table("orders")
            .WithColumn("id")
            .AsInt64()
            .PrimaryKey()
            .Identity()
            .WithColumn("pipeline_id")
            .AsInt32()
            .Nullable()
            .ForeignKey("pipeline_configurations", "id")
            .WithColumn("market_type")
            .AsInt32()
            .NotNullable()
            .WithColumn("exchange_order_id")
            .AsString(100)
            .NotNullable()
            .WithColumn("symbol")
            .AsString(20)
            .NotNullable()
            .WithColumn("side")
            .AsInt32()
            .NotNullable()
            .WithColumn("status")
            .AsInt32()
            .NotNullable()
            .WithColumn("quantity")
            .AsDecimal(28, 10)
            .NotNullable()
            .WithColumn("price")
            .AsDecimal(28, 10)
            .Nullable()
            .WithColumn("stop_price")
            .AsDecimal(28, 10)
            .Nullable()
            .WithColumn("fee")
            .AsDecimal(28, 10)
            .Nullable()
            .WithColumn("placed_at")
            .AsDateTime()
            .Nullable()
            .WithColumn("executed_at")
            .AsDateTime()
            .Nullable()
            .WithColumn("cancelled_at")
            .AsDateTime()
            .Nullable()
            .WithColumn("take_profit")
            .AsDecimal(28, 10)
            .Nullable()
            .WithColumn("stop_loss")
            .AsDecimal(28, 10)
            .Nullable()
            .WithColumn("created_at")
            .AsDateTime()
            .NotNullable()
            .WithColumn("updated_at")
            .AsDateTime()
            .NotNullable()
        |> ignore

        this.Create.Index().OnTable("orders").OnColumn("pipeline_id").Ascending() |> ignore
        this.Create.Index().OnTable("orders").OnColumn("symbol").Ascending() |> ignore

    override this.Down() =
        this.Delete.Table("orders") |> ignore
        this.Delete.Table("pipeline_steps") |> ignore
        this.Delete.Table("candlesticks") |> ignore
        this.Delete.Table("positions") |> ignore
        this.Delete.Table("pipeline_configurations") |> ignore
        this.Delete.Table("market_credentials") |> ignore
        this.Delete.Table("markets") |> ignore
