using Warehouse.Core.Markets.Domain;
using Warehouse.Core.Orders.Domain;

namespace Warehouse.Core.Orders.Models;

/// <summary>
///     Parameters for creating a new order.
/// </summary>
public class CreateOrderRequest
{
    /// <summary>
    ///     Optional pipeline ID if this order is generated by an automated pipeline.
    /// </summary>
    public int? PipelineId { get; init; }

    /// <summary>
    ///     The market type for the order.
    /// </summary>
    public required MarketType MarketType { get; init; }

    /// <summary>
    ///     The trading pair symbol (e.g., "BTCUSDT").
    /// </summary>
    public required string Symbol { get; init; }

    /// <summary>
    ///     The side of the order (Buy or Sell).
    /// </summary>
    public required OrderSide Side { get; init; }

    /// <summary>
    ///     Base asset quantity to trade.
    /// </summary>
    public required decimal Quantity { get; init; }

    /// <summary>
    ///     Limit price. If null, treated as Market order.
    /// </summary>
    public decimal? Price { get; init; }

    /// <summary>
    ///     Trigger price (for stop-loss/take-profit triggers).
    /// </summary>
    public decimal? StopPrice { get; init; }

    public decimal? TakeProfit { get; init; }

    public decimal? StopLoss { get; init; }

    public DateTime? ExpireTime { get; set; }
}
